# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "nest-hr-system"

[api]
# Port to use for the API URL.
port = 54421
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API endpoints.
# public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returned from a table, view, or stored procedure. Limits payload size for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54422
# Port used by db diff command to initialize the shadow database.
shadow_port = 54420
# The database major version to use. This has to be the same as your remote database's major version.
# 15 is the latest supported version.
major_version = 15

[db.pooler]
# Port to use for the local connection pooler.
port = 54429

[realtime]
# Set to false to disable realtime functionality.
enabled = true

[studio]
# Port to use for Supabase Studio.
port = 54423
# External URL of the API server that frontend connects to.
# This is the URL that appears in the API settings in the dashboard.
api_url = "http://localhost:54421"

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
# Port to use for the email testing server web interface.
port = 54424
# Uncomment to expose additional ports for testing user applications that send emails.
# smtp_port = 2500
# pop3_port = 1100

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604800 (one week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email addresses.
# If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

# Uncomment to customize email template
# [auth.email.template.invite]
# subject = "You have been invited"
# content_path = "./supabase/templates/invite.html"

[auth.sms]
# Allow/disallow new user signups via SMS to your project.
enable_signup = true
# If enabled, users need to confirm their phone number before signing in.
enable_confirmations = false
# Template for sending a confirmation message when a user signs up with a phone number.
# {{ .Code }} is the verification code.
template = "Your code is {{ .Code }}"

[auth.external.apple]
# Apple OAuth provider configuration.
enabled = false
# OAuth client identifier.
client_id = ""
# OAuth client secret.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.azure]
# Azure OAuth provider configuration.
enabled = false
# OAuth client identifier.
client_id = ""
# OAuth client secret.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.bitbucket]
# Bitbucket OAuth provider configuration.
enabled = false
# OAuth client identifier.
client_id = ""
# OAuth client secret.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.discord]
# Discord OAuth provider configuration.
enabled = false
# OAuth client identifier.
client_id = ""
# OAuth client secret.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.facebook]
# Facebook OAuth provider configuration.
enabled = false
# OAuth client identifier.
client_id = ""
# OAuth client secret.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.github]
# GitHub OAuth provider configuration.
enabled = false
# OAuth client identifier.
client_id = ""
# OAuth client secret.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.gitlab]
# GitLab OAuth provider configuration.
enabled = false
# OAuth client identifier.
client_id = ""
# OAuth client secret.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.google]
# Google OAuth provider configuration.
enabled = false
# OAuth client identifier.
client_id = ""
# OAuth client secret.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.keycloak]
# Keycloak OAuth provider configuration.
enabled = false
# OAuth client identifier.
client_id = ""
# OAuth client secret.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.linkedin]
# LinkedIn OAuth provider configuration.
enabled = false
# OAuth client identifier.
client_id = ""
# OAuth client secret.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.notion]
# Notion OAuth provider configuration.
enabled = false
# OAuth client identifier.
client_id = ""
# OAuth client secret.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.slack]
# Slack OAuth provider configuration.
enabled = false
# OAuth client identifier.
client_id = ""
# OAuth client secret.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.spotify]
# Spotify OAuth provider configuration.
enabled = false
# OAuth client identifier.
client_id = ""
# OAuth client secret.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.twitch]
# Twitch OAuth provider configuration.
enabled = false
# OAuth client identifier.
client_id = ""
# OAuth client secret.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.twitter]
# Twitter OAuth provider configuration.
enabled = false
# OAuth client identifier.
client_id = ""
# OAuth client secret.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.workos]
# WorkOS OAuth provider configuration.
enabled = false
# OAuth client identifier.
client_id = ""
# OAuth client secret.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.zoom]
# Zoom OAuth provider configuration.
enabled = false
# OAuth client identifier.
client_id = ""
# OAuth client secret.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[edge_runtime]
# Edge Runtime configuration
